

name: CICD

on:
  push:
    branches:
      - test-CICD

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Deploy to Elastic Beanstalk
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-east-1'
          run: |
            pip install awscli
            aws elasticbeanstalk update-environment \
                --application-name Test \
                --environment-name Test-env \
                --version-label 2.0.0 \
                --region us-east-1