name: CICD

on:
  push:
    branches:
      - test-CICD

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Install EB CLI and AWS CLI
          run: |
            pip install awsebcli awscli
        
        - name: Deploy to Elastic Beanstalk
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-east-1'
          run: |
            # Initialize EB CLI (you might have already done this locally, but this is to ensure it works in the CI/CD environment). 
            # This might ask for the region, application name, and other details. You'll want to fill these in for the CI/CD environment.
            # eb init <application-name> --region <region-name> 

            # Create a new application version and deploy it
            eb deploy -l 2.0.0
