name: deploy-to-eb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
    
      - name: node install
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install npm dependencies
        run: npm install
      
      - name: Build Website Assets
        run: npm run build 

      - name: create zip deployment package
        run: zip -r deploy_package.zip .next pages public styles *.json *.js *.ts

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          application_name: SeeQR-Website
          environment_name: SeeQR-Website-env
          version_label: "ver-${{ github.sha }}"
          existing_bucket_name: seeqr-splash-page-deploy
          region: us-west-1
          deployment_package: node.js.zip