name: deploy-to-eb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
    
      - name: node install
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install npm dependencies
        run: npm install
      
      - name: Build Website Assets
        run: npm run build 

      - name: create zip deployment package
        run: zip -r deploy_package3.zip .next pages public styles *.json *.js *.ts

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          application_name: SeeQR-Website
          environment_name: SeeQR-Website-env
          version_label: "ver-${{ github.sha }}"
          region: us-west-1
          deployment_package: deploy_package3.zip
      
      
      
      # - name: configure aws credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
      #     aws-region: "us-west-1"

      # - name: upload deployment package to s3 bucket
      #   run: aws s3 cp deploy_package_fromAction.zip s3://seeqr-splash-page-deploy/



      # - name: Create new ElasticBeanstalk Application Version
      #   run: |
      #     aws elasticbeanstalk create-application-version \
      #     --application-name SeeQR-Website \
      #     --source-bundle S3Bucket="seeqr-splash-page-deploy",S3Key="deploy_package.zip" \
      #     --version-label "ver-${{ github.sha }}" \
      #     --description "commit-sha-${{ github.sha }}"

      # - name: Deploy New ElasticBeanstalk Application Version
      #   run: aws elasticbeanstalk update-environment --environment-name SeeQR-Website-env --version-label "ver-${{ github.sha }}"